### ISSUE TITLE
Design Notes

### ISSUE THREAD

**Issue by maektwain** [Cynsar-Foundation/second.exchange#1]
This will serve as a design notes 

## Intro 

So, we need some contracts that does this

1. Create and Non Fungible Assets on the different selected chains as of now we can choose to stay on single then later add more--
2. Ability to store and map the CID or vice-versa from distributed file system, 
3. Should we use ENS style registry to map the document and label them externally ?

**Comment by PulkitVyasCynsar** [comment]
Closing for irrelevance
