### ISSUE TITLE
Add toast messages 

### ISSUE THREAD

**Issue by maektwain** [Cynsar-Foundation/second.exchange#13]
About everything, lets do this so that we avoid these null related issues , undefined issues, issues that are not covered, 

1. If the user interacts and gets an error say issues or bug> then we should report that on Github and at the same time reports to the user that we are notified and will fix this issue and ask the user to try again.

**Comment by pulkitvyas08** [comment]
> 1. If the user interacts and gets an error say issues or bug> then we should report that on Github and at the same time reports to the user that we are notified and will fix this issue and ask the user to try again.

Report on GitHub as in open a new issue related to that bug?

**Comment by maektwain** [comment]
Before you start with anything , lets define more ideas before your start !

**Comment by KevalGondaliya** [comment]
I just resolving bugs

**Comment by pulkitvyas08** [comment]
Added in #16
