### ISSUE TITLE
A new navbar from scratch

### ISSUE THREAD

**Issue by pulkitvyas08** [Cynsar-Foundation/second.exchange#18]
The current navbar has many issues:
- Not responsive
- Navigation elements are spaced with forced styling and so the active page indicator (the black rectangle in the background) is placed as a hack
- Wallet button is also not responsive

**Comment by ishubhamk-cynsar** [comment]
This issue was related to the navbar in old UI, responsive design is relevant for the entire application including UI but we will be creating separate issues and deal with it incrementally in coming weeks.
