### ISSUE TITLE
Update the token/coin name and logo with the users'

### ISSUE THREAD

**Issue by pulkitvyas08** [Cynsar-Foundation/second.exchange#19]
![image](https://user-images.githubusercontent.com/54947769/147350877-7d62bcb0-3d63-481d-a706-109745656e42.png)
This (`/src/components/UserInfoSectionRect.jsx`) takes in token/coin name and logo from Sidebar component (`/src/components/layout/Sidebar.jsx`). 
In the sidebar, we need to update the name and logo with the coin/token the user is using for transactions

**Comment by maektwain** [comment]
We should think of removing the Logo since its not usable at all
