### ISSUE TITLE
Update wallet definitions with Moralis API

### ISSUE THREAD

**Issue by pulkitvyas08** [Cynsar-Foundation/second.exchange#20]
Right now only MetaMask is configured with Moralis API (`/src/components/WalletModal.jsx`), the other three (Portis, Torus, WalletConnect) also need to be configured with the same.
MetaMask has native support for WalletConnect (refer: https://moralis.io/how-to-connect-users-with-walletconnect/). For Portis and Torus custom wallet providers might be needed (refer: https://docs.moralis.io/moralis-server/users/crypto-login#custom-wallet-login, https://forum.moralis.io/t/how-to-authenticate-signin-with-portis-and-torus-wallets/2059/11)

**Comment by maektwain** [comment]
Lets close this since this is not usable 

Thanks for the work done so far !
