### ISSUE TITLE
Fix CI/CD

### ISSUE THREAD

**Issue by ishubhamk-cynsar** [Cynsar-Foundation/second.exchange#49]
Current deployment of UI happens on a github io. It is attached to @pulkitvyas08 account resulting in `second.exchange` route slug in each route. We can migrate over to netlify so that ui deployment can happen there. Once we decide over domain name mechanism either through metaroot or conventional dns we can start pointing to netlify

**Comment by PulkitVyasCynsar** [comment]
No, the current deployment is attached to `cynsar-foundation.github.io` but yes if we migrate somewhere then the `second.exchange` route slug won't be needed anymore

**Comment by ishubhamk-cynsar** [comment]
As discussed in the discord channel, this is one potential scheme
1. Create a site in netlify and attach domain second.exchange, this will become production deployment site
2. Create another site in netlify and attach a subdomain like dev.second.exchange, this will be dev merge site
3. Every merge in development should be automated to be deployed on dev.second.exchange.
4. Every release should be automated to be deployed on second.exchange.
5. Every pull request, every commit should execute unit tests

**Comment by PulkitVyasCynsar** [comment]
Will be done by Vercel now
