### ISSUE TITLE
Fix single article view

### ISSUE THREAD

**Issue by ishubhamk-cynsar** [Cynsar-Foundation/second.exchange#67]
Diverting a bit from the bug report template because the app is not deployed yet, will be very difficult to reproduce

Currently on the single article view reload will take you back to the home screen. This is to get around an issue for getting individual articles from nostr relay.

What needs to be done? We are anyway getting the list of events from the relay, just pick the public id of event from the url slug and search for it in the event list and display it accordingly. We need to create a subsciption for `event-children` to get the messages in an individual article but commenting on the article is not the target for this initial release

**Comment by ishubhamk-cynsar** [comment]
As discussed with @PulkitVyasCynsar one potential problem with this approach is that there is no way we can get when the event list is completely full in other words how can we know that the nost-relay is done with getting all the events so that we can search for a particular event in the event list.
In my opinion we need to experiment a bit for this one, branle client has the same functionality so probably we can steal some of it from there.

**Comment by PulkitVyasCynsar** [comment]
Closing for irrelevance. Branle architecture fixes thsi
