### ISSUE TITLE
Ability to search for users and their content using their public address

### ISSUE THREAD

**Issue by ishubhamk-cynsar** [Cynsar-Foundation/second.exchange#70]
We have a search bar in the header, need to integrate proper filter with relay and event in order to search and follow users

**Comment by maektwain** [comment]
Could we implement the DID's where tags can be filtered or names

**Comment by ishubhamk-cynsar** [comment]
Yes, if I am not wrong it is already there in nostr protocol. We will start off with public address, since it is the easiest and then look into decentralized identities based event filtering.

**Comment by PulkitVyasCynsar** [comment]
Implemented in #78
