### ISSUE TITLE
Please improve development setup

### ISSUE THREAD

**Issue by maektwain** [Cynsar-Foundation/second.exchange#73]
**Is your feature request related to a problem? Please describe.**
Right now to setup dev env there are certain steps that needs be taken like multiple dir and this and that 

**Describe the solution you'd like**
Can we reduce this to a single step ?

**Describe alternatives you've considered**

**Additional context**

**Comment by PulkitVyasCynsar** [comment]
As of now, with the branle architecture this can be done in just two steps. Closing this for irrelevance
