### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by pulkitvyas08** [Cynsar-Foundation/second.exchange#9]
- [x] Create CI pipeline with GH Actions
- [x] Add truffle tests for Web3 integrations
- [x] Add unit tests for states

**Comment by ishubhamk-cynsar** [comment]
Thanks @PulkitVyasCynsar this will serve as a base for the unit test and CI/CD integration which we are tracking in #48 and #49 respectively. Closing this in favor of other issues
